apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "backend.fullname" . }}-migrations
  labels:
    {{- include "backend.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "-1"
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  backoffLimit: 3
  template:
    metadata:
      name: {{ include "backend.fullname" . }}-migrations
      labels:
        {{- include "backend.labels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrations
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - python
            - manage.py
            - migrate
            - --noinput
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "backend.fullname" . }}-secret
                  key: SECRET_KEY
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  name: {{ include "backend.fullname" . }}-env
                  key: DEBUG
            - name: ALLOWED_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "backend.fullname" . }}-env
                  key: ALLOWED_HOSTS
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ include "backend.fullname" . }}-env
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "backend.fullname" . }}-env
                  key: POSTGRES_USER
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "backend.fullname" . }}-env
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "backend.fullname" . }}-env
                  key: POSTGRES_PORT
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "backend.fullname" . }}-secret
                  key: POSTGRES_PASSWORD
            - name: CORS_ALLOWED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "backend.fullname" . }}-env
                  key: CORS_ALLOWED_ORIGINS
            - name: CSRF_TRUSTED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "backend.fullname" . }}-env
                  key: CSRF_TRUSTED_ORIGINS
