apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-secret
  labels:
    {{- include "backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: django-insecure-default-key-change-in-production
  POSTGRES_PASSWORD: pistemaster123
