# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller spec file for PisteMaster backend

Build command:
    pyinstaller PisteMaster.spec --noconfirm --clean

Output:
    dist/pistemaster-backend/ (Windows folder with .exe)
"""

import sys
from pathlib import Path

block_cipher = None

backend_dir = Path('.').resolve()
project_root = backend_dir.parent

a = Analysis(
    ['run_desktop.py'],
    pathex=[str(backend_dir), str(project_root)],
    binaries=[],
    datas=[
        ('PisteMaster/settings', 'PisteMaster/settings'),
        (str(project_root / 'core'), 'core'),
        ('apps', 'backend/apps'),
        ('apps/users', 'backend/apps/users'),
        ('apps/cluster', 'backend/apps/cluster'),
    ],
    hiddenimports=[
        'django',
        'django.contrib',
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
        'rest_framework',
        'corsheaders',
        'django_filters',
        'backend',
        'backend.apps',
        'backend.apps.fencing_organizer',
        'backend.apps.fencing_organizer.apps',
        'backend.apps.fencing_organizer.urls',
        'backend.apps.fencing_organizer.modules',
        'backend.apps.fencing_organizer.modules.event',
        'backend.apps.fencing_organizer.modules.event.models',
        'backend.apps.fencing_organizer.modules.event.views',
        'backend.apps.fencing_organizer.modules.event.serializers',
        'backend.apps.fencing_organizer.modules.event.urls',
        'backend.apps.fencing_organizer.modules.event_participant',
        'backend.apps.fencing_organizer.modules.event_participant.models',
        'backend.apps.fencing_organizer.modules.event_participant.views',
        'backend.apps.fencing_organizer.modules.event_participant.serializers',
        'backend.apps.fencing_organizer.modules.event_participant.urls',
        'backend.apps.fencing_organizer.modules.fencer',
        'backend.apps.fencing_organizer.modules.fencer.models',
        'backend.apps.fencing_organizer.modules.fencer.views',
        'backend.apps.fencing_organizer.modules.fencer.serializers',
        'backend.apps.fencing_organizer.modules.fencer.urls',
        'backend.apps.fencing_organizer.modules.pool',
        'backend.apps.fencing_organizer.modules.pool.models',
        'backend.apps.fencing_organizer.modules.pool.views',
        'backend.apps.fencing_organizer.modules.pool.serializers',
        'backend.apps.fencing_organizer.modules.pool.urls',
        'backend.apps.fencing_organizer.modules.pool_assignment',
        'backend.apps.fencing_organizer.modules.pool_assignment.models',
        'backend.apps.fencing_organizer.modules.pool_assignment.views',
        'backend.apps.fencing_organizer.modules.pool_assignment.serializers',
        'backend.apps.fencing_organizer.modules.pool_assignment.urls',
        'backend.apps.fencing_organizer.modules.pool_bout',
        'backend.apps.fencing_organizer.modules.pool_bout.models',
        'backend.apps.fencing_organizer.modules.pool_bout.views',
        'backend.apps.fencing_organizer.modules.pool_bout.serializers',
        'backend.apps.fencing_organizer.modules.pool_bout.urls',
        'backend.apps.fencing_organizer.modules.piste',
        'backend.apps.fencing_organizer.modules.piste.models',
        'backend.apps.fencing_organizer.modules.piste.views',
        'backend.apps.fencing_organizer.modules.rule',
        'backend.apps.fencing_organizer.modules.rule.models',
        'backend.apps.fencing_organizer.modules.rule.views',
        'backend.apps.fencing_organizer.modules.rule.serializers',
        'backend.apps.fencing_organizer.modules.rule.urls',
        'backend.apps.fencing_organizer.modules.tournament',
        'backend.apps.fencing_organizer.modules.tournament.models',
        'backend.apps.fencing_organizer.modules.tournament.views',
        'backend.apps.fencing_organizer.modules.tournament.serializers',
        'backend.apps.fencing_organizer.modules.tournament.urls',
        'backend.apps.fencing_organizer.modules.tournament_status',
        'backend.apps.fencing_organizer.modules.tournament_status.models',
        'backend.apps.fencing_organizer.modules.tournament_status.views',
        'backend.apps.fencing_organizer.modules.tournament_status.urls',
        'backend.apps.fencing_organizer.repositories',
        'backend.apps.fencing_organizer.repositories.tournament_repo',
        'backend.apps.fencing_organizer.repositories.event_repo',
        'backend.apps.fencing_organizer.repositories.fencer_repo',
        'backend.apps.fencing_organizer.repositories.pool_repo',
        'backend.apps.fencing_organizer.services',
        'backend.apps.fencing_organizer.services.tournament_service',
        'backend.apps.fencing_organizer.services.event_service',
        'backend.apps.fencing_organizer.services.pool_service',
        'backend.apps.fencing_organizer.mappers',
        'backend.apps.fencing_organizer.mappers.pool_mapper',
        'backend.apps.fencing_organizer.utils',
        'backend.apps.fencing_organizer.utils.pagination',
        'backend.apps.users',
        'backend.apps.users.apps',
        'backend.apps.users.models',
        'backend.apps.users.views',
        'backend.apps.users.serializers',
        'backend.apps.users.urls',
        'backend.apps.users.migrations',
        'backend.apps.cluster',
        'backend.apps.cluster.apps',
        'backend.apps.cluster.models',
        'backend.apps.cluster.serializers',
        'backend.apps.cluster.views',
        'backend.apps.cluster.urls',
        'backend.apps.cluster.migrations',
        'backend.apps.cluster.middleware',
        'backend.apps.cluster.decorators',
        'backend.apps.cluster.services',
        'backend.apps.cluster.schemas',
        'core',
        'core.models',
        'core.models.tournament',
        'core.models.event',
        'core.models.fencer',
        'core.models.pool',
        'core.interfaces',
        'core.interfaces.tournament_repository',
        'core.interfaces.event_repository',
        'core.interfaces.fencer_repository',
        'core.interfaces.pool_repository',
        'core.constants',
        'core.constants.pool',
        'PisteMaster',
        'PisteMaster.settings',
        'PisteMaster.settings.base',
        'PisteMaster.settings.development',
        'PisteMaster.settings.production',
        'PisteMaster.settings.desktop',
        'PisteMaster.urls',
        'PisteMaster.wsgi',
    ],
    hookspath=['./hooks'],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'unittest',
        'test',
        'tests',
        'pytest',
        'flake8',
        'black',
        'ipython',
        'PySide6',
        'PySide6.QtCore',
        'PySide6.QtGui',
        'PySide6.QtWidgets',
        'drf_yasg',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='pistemaster-backend',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,  
    console=True,  
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='pistemaster-backend',
)