# Generated by Django 4.2.29 on 2026-03-31 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DjangoSyncState",
            fields=[
                (
                    "node_id",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, verbose_name="Unique identifier of the follower node"
                    ),
                ),
                ("last_synced_id", models.BigIntegerField(default=0, verbose_name="Last sync_log ID that was successfully applied")),
                ("last_sync_time", models.DateTimeField(auto_now=True, verbose_name="Timestamp of last successful sync")),
            ],
            options={
                "verbose_name": "Sync State",
                "verbose_name_plural": "Sync States",
                "db_table": "sync_state",
            },
        ),
        migrations.CreateModel(
            name="DjangoSyncLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("table_name", models.CharField(max_length=100, verbose_name="Table/entity name")),
                ("record_id", models.CharField(max_length=100, verbose_name="Primary key of the changed record")),
                ("operation", models.CharField(help_text="INSERT, UPDATE, or DELETE", max_length=10, verbose_name="Operation type")),
                ("data", models.JSONField(verbose_name="JSON data of the change")),
                ("version", models.BigIntegerField(default=1, verbose_name="Version number for conflict resolution")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Timestamp when log was created")),
            ],
            options={
                "verbose_name": "Sync Log",
                "verbose_name_plural": "Sync Logs",
                "db_table": "sync_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["table_name"], name="idx_sync_log_table"),
                    models.Index(fields=["record_id"], name="idx_sync_log_record"),
                    models.Index(fields=["created_at"], name="idx_sync_log_created"),
                    models.Index(fields=["table_name", "record_id"], name="idx_sync_log_table_record"),
                ],
            },
        ),
    ]
