# Generated by Django 4.2.29 on 2026-04-04 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cluster", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="djangosynclog",
            name="record_id",
            field=models.CharField(max_length=100, verbose_name="Primary key of changed record"),
        ),
        migrations.AlterField(
            model_name="djangosyncstate",
            name="last_synced_id",
            field=models.BigIntegerField(default=0, verbose_name="Last sync_log ID successfully applied"),
        ),
        migrations.AlterField(
            model_name="djangosyncstate",
            name="node_id",
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name="Unique identifier of follower node"),
        ),
    ]
