# Generated by Django 4.2.29 on 2026-04-05 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cluster", "0002_alter_djangosynclog_record_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DjangoClusterConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("singleton_id", models.IntegerField(default=1, unique=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[("single", "Single Node"), ("cluster", "Cluster")],
                        default="single",
                        max_length=20,
                        verbose_name="Cluster Mode",
                    ),
                ),
                ("node_id", models.CharField(blank=True, max_length=100, null=True, verbose_name="Node ID")),
                ("udp_port", models.IntegerField(default=9000, verbose_name="UDP Port")),
                ("api_port", models.IntegerField(default=8000, verbose_name="API Port")),
                ("heartbeat_interval", models.FloatField(default=5.0, verbose_name="Heartbeat Interval")),
                ("heartbeat_timeout", models.FloatField(default=15.0, verbose_name="Heartbeat Timeout")),
                ("sync_interval", models.FloatField(default=3.0, verbose_name="Sync Interval")),
                ("replica_ack_required", models.IntegerField(default=1, verbose_name="Replica ACK Required")),
                ("ack_timeout_ms", models.IntegerField(default=5000, verbose_name="ACK Timeout (ms)")),
                ("master_ip", models.CharField(blank=True, max_length=50, null=True, verbose_name="Master IP")),
                ("is_master", models.BooleanField(default=False, verbose_name="Is Master")),
                ("master_url", models.CharField(blank=True, max_length=200, null=True, verbose_name="Master URL")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cluster Configuration",
                "verbose_name_plural": "Cluster Configuration",
                "db_table": "cluster_config",
            },
        ),
    ]
