# Generated by Django 4.2.29 on 2026-04-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cluster", "0003_add_cluster_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="djangosyncstate",
            name="url",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="HTTP endpoint URL of follower node for push notifications"
            ),
        ),
    ]
