# Generated by Django 4.2.29 on 2026-04-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cluster", "0004_djangosyncstate_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="djangosyncstate",
            name="master_latest_sync_id",
            field=models.BigIntegerField(default=0, verbose_name="Latest sync_log ID on master at time of last sync pull"),
        ),
    ]
