# Generated by Django 4.2.29 on 2026-04-04 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_fix_guest_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("ADMIN", "Admin"), ("SCHEDULER", "Scheduler"), ("GUEST", "Guest")],
                default="SCHEDULER",
                max_length=20,
                verbose_name="role",
            ),
        ),
    ]
