image:
  repository: postgres
  tag: 16-alpine
  pullPolicy: IfNotPresent

persistence:
  enabled: true
  size: 2Gi
  storageClass: local-path

database: pistemaster
username: pistemaster

resources: {}
