# Generated by Django 4.2.27 on 2025-12-11 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fencing_organizer", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DjangoFencer",
        ),
    ]
