# Generated by Django 4.2.27 on 2025-12-11 13:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fencing_organizer", "0002_delete_djangofencer"),
    ]

    operations = [
        migrations.CreateModel(
            name="DjangoFencer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("gender", models.CharField(blank=True, max_length=10, null=True)),
                ("country_code", models.CharField(blank=True, max_length=3, null=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "fencing_id",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("current_ranking", models.IntegerField(blank=True, null=True)),
                (
                    "primary_weapon",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "fencer",
                "indexes": [
                    models.Index(fields=["country_code"], name="idx_fencer_country"),
                    models.Index(
                        fields=["last_name", "first_name"], name="idx_fencer_name"
                    ),
                    models.Index(fields=["fencing_id"], name="idx_fencer_fencing_id"),
                ],
            },
        ),
    ]
