# Generated by Django 4.2.27 on 2025-12-13 10:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("fencing_organizer", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DjangoTournamentStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status_code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="状态代码"
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="显示名称"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="描述"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "赛事状态",
                "verbose_name_plural": "赛事状态",
                "db_table": "tournament_status",
                "ordering": ["status_code"],
            },
        ),
        migrations.CreateModel(
            name="DjangoTournament",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tournament_name",
                    models.CharField(
                        max_length=200,
                        validators=[django.core.validators.MinLengthValidator(1)],
                        verbose_name="赛事名称",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="开始日期")),
                ("end_date", models.DateField(verbose_name="结束日期")),
                (
                    "organizer",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="主办方"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="赛事举办地"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.ForeignKey(
                        db_column="status_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tournaments",
                        to="fencing_organizer.djangotournamentstatus",
                        verbose_name="赛事状态",
                    ),
                ),
            ],
            options={
                "verbose_name": "赛事",
                "verbose_name_plural": "赛事",
                "db_table": "tournament",
                "ordering": ["-start_date", "tournament_name"],
                "indexes": [
                    models.Index(
                        fields=["start_date", "end_date"], name="idx_tournament_dates"
                    ),
                    models.Index(fields=["status"], name="idx_tournament_status"),
                    models.Index(
                        fields=["tournament_name"], name="idx_tournament_name"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="djangotournament",
            constraint=models.CheckConstraint(
                check=models.Q(("end_date__gte", models.F("start_date"))),
                name="chk_tournament_dates_valid",
            ),
        ),
    ]
