# Generated by Django 4.2.27 on 2025-12-13 10:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("fencing_organizer", "0004_djangotournamentstatus_djangotournament_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DjangoEliminationType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type_code",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="类型代码"
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="显示名称"
                    ),
                ),
            ],
            options={
                "verbose_name": "淘汰赛类型",
                "verbose_name_plural": "淘汰赛类型",
                "db_table": "elimination_type",
                "ordering": ["type_code"],
            },
        ),
        migrations.CreateModel(
            name="DjangoRankingType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type_code",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="类型代码"
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="显示名称"
                    ),
                ),
            ],
            options={
                "verbose_name": "排名类型",
                "verbose_name_plural": "排名类型",
                "db_table": "ranking_type",
                "ordering": ["type_code"],
            },
        ),
        migrations.CreateModel(
            name="DjangoRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rule_name",
                    models.CharField(max_length=100, verbose_name="规则名称"),
                ),
                (
                    "total_qualified_count",
                    models.IntegerField(verbose_name="总晋级人数"),
                ),
                (
                    "match_format",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="单场比赛格式",
                    ),
                ),
                (
                    "pool_size",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="小组赛每组人数"
                    ),
                ),
                (
                    "match_duration",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="单局时长（秒）"
                    ),
                ),
                (
                    "match_score_pool",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="小组赛目标分数"
                    ),
                ),
                (
                    "match_score_elimination",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="淘汰赛目标分数"
                    ),
                ),
                (
                    "group_qualification_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=5,
                        null=True,
                        verbose_name="晋级比例",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="规则描述"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "elimination_type",
                    models.ForeignKey(
                        db_column="elimination_type_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rules",
                        to="fencing_organizer.djangoeliminationtype",
                        verbose_name="淘汰赛类型",
                    ),
                ),
                (
                    "final_ranking_type",
                    models.ForeignKey(
                        db_column="final_ranking_type_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rules",
                        to="fencing_organizer.djangorankingtype",
                        verbose_name="名次决出方式",
                    ),
                ),
            ],
            options={
                "verbose_name": "赛制规则",
                "verbose_name_plural": "赛制规则",
                "db_table": "rule",
                "ordering": ["rule_name"],
                "indexes": [
                    models.Index(
                        fields=["elimination_type"], name="idx_rule_elimination_type"
                    ),
                    models.Index(
                        fields=["final_ranking_type"], name="idx_rule_ranking_type"
                    ),
                    models.Index(fields=["pool_size"], name="idx_rule_pool_size"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="djangorule",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("pool_size__gte", 3), ("pool_size__isnull", True), _connector="OR"
                ),
                name="chk_rule_pool_size",
            ),
        ),
        migrations.AddConstraint(
            model_name="djangorule",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("group_qualification_ratio__gte", 0),
                        ("group_qualification_ratio__lte", 1),
                    ),
                    ("group_qualification_ratio__isnull", True),
                    _connector="OR",
                ),
                name="chk_rule_qualification_ratio",
            ),
        ),
    ]
