# Generated by Django 4.2.27 on 2025-12-13 13:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        (
            "fencing_organizer",
            "0005_djangoeliminationtype_djangorankingtype_djangorule_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DjangoEventStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status_code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="状态代码"
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="显示名称"
                    ),
                ),
            ],
            options={
                "verbose_name": "项目状态",
                "verbose_name_plural": "项目状态",
                "db_table": "event_status",
                "ordering": ["status_code"],
            },
        ),
        migrations.CreateModel(
            name="DjangoEventType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type_code",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="类型代码"
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="显示名称"
                    ),
                ),
                (
                    "weapon_type",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="剑种"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="性别"
                    ),
                ),
            ],
            options={
                "verbose_name": "项目类型",
                "verbose_name_plural": "项目类型",
                "db_table": "event_type",
                "ordering": ["type_code"],
                "indexes": [
                    models.Index(fields=["weapon_type"], name="idx_event_type_weapon"),
                    models.Index(fields=["gender"], name="idx_event_type_gender"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DjangoEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_name",
                    models.CharField(
                        max_length=200,
                        validators=[django.core.validators.MinLengthValidator(1)],
                        verbose_name="项目名称",
                    ),
                ),
                (
                    "is_team_event",
                    models.BooleanField(default=False, verbose_name="是否为团体赛"),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="项目开始时间"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.ForeignKey(
                        db_column="event_type_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="fencing_organizer.djangoeventtype",
                        verbose_name="项目类型",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        db_column="rule_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="fencing_organizer.djangorule",
                        verbose_name="赛制规则",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        db_column="status_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="fencing_organizer.djangoeventstatus",
                        verbose_name="项目状态",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        db_column="tournament_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="fencing_organizer.djangotournament",
                        verbose_name="所属赛事",
                    ),
                ),
            ],
            options={
                "verbose_name": "比赛项目",
                "verbose_name_plural": "比赛项目",
                "db_table": "event",
                "ordering": ["start_time", "event_name"],
                "indexes": [
                    models.Index(fields=["tournament"], name="idx_event_tournament"),
                    models.Index(fields=["status"], name="idx_event_status"),
                    models.Index(fields=["event_type"], name="idx_event_type"),
                    models.Index(fields=["start_time"], name="idx_event_start_time"),
                    models.Index(fields=["is_team_event"], name="idx_event_is_team"),
                ],
            },
        ),
    ]
