# Generated by Django 4.2.27 on 2025-12-14 08:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("fencing_organizer", "0006_djangoeventstatus_djangoeventtype_djangoevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="DjangoMatchStatusType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status_code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="状态代码"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="描述"
                    ),
                ),
            ],
            options={
                "verbose_name": "比赛状态",
                "verbose_name_plural": "比赛状态",
                "db_table": "match_status_type",
                "ordering": ["status_code"],
            },
        ),
        migrations.CreateModel(
            name="DjangoPiste",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "piste_number",
                    models.CharField(max_length=10, verbose_name="剑道编号"),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="具体位置"
                    ),
                ),
                (
                    "piste_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MAIN", "主剑道"),
                            ("SIDE", "副剑道"),
                            ("WARMUP", "热身剑道"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="剑道类型",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="是否可用"),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="备注")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tournament",
                    models.ForeignKey(
                        db_column="tournament_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pistes",
                        to="fencing_organizer.djangotournament",
                        verbose_name="所属赛事",
                    ),
                ),
            ],
            options={
                "verbose_name": "剑道",
                "verbose_name_plural": "剑道",
                "db_table": "piste",
                "ordering": ["tournament", "piste_number"],
            },
        ),
        migrations.CreateModel(
            name="DjangoPool",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pool_number",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="小组编号",
                    ),
                ),
                (
                    "pool_letter",
                    models.CharField(
                        blank=True, max_length=1, null=True, verbose_name="小组字母"
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "SCHEDULED"),
                            ("READY", "READY"),
                            ("IN_PROGRESS", "IN_PROGRESS"),
                            ("COMPLETED", "COMPLETED"),
                            ("CANCELLED", "CANCELLED"),
                            ("POSTPONED", "POSTPONED"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="是否完成"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        db_column="event_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pools",
                        to="fencing_organizer.djangoevent",
                        verbose_name="所属项目",
                    ),
                ),
                (
                    "piste",
                    models.ForeignKey(
                        blank=True,
                        db_column="piste_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pools",
                        to="fencing_organizer.djangopiste",
                        verbose_name="分配剑道",
                    ),
                ),
            ],
            options={
                "verbose_name": "小组",
                "verbose_name_plural": "小组",
                "db_table": "pool",
                "ordering": ["event", "pool_number"],
            },
        ),
        migrations.CreateModel(
            name="DjangoPoolBout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fencer_a_score",
                    models.IntegerField(default=0, verbose_name="A得分"),
                ),
                (
                    "fencer_b_score",
                    models.IntegerField(default=0, verbose_name="B得分"),
                ),
                (
                    "scheduled_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="计划时间"
                    ),
                ),
                (
                    "actual_start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="实际开始时间"
                    ),
                ),
                (
                    "actual_end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="实际结束时间"
                    ),
                ),
                (
                    "duration_seconds",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="持续时间（秒）"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="备注")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fencer_a",
                    models.ForeignKey(
                        db_column="fencer_a_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pool_bouts_as_a",
                        to="fencing_organizer.djangofencer",
                        verbose_name="运动员A",
                    ),
                ),
                (
                    "fencer_b",
                    models.ForeignKey(
                        db_column="fencer_b_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pool_bouts_as_b",
                        to="fencing_organizer.djangofencer",
                        verbose_name="运动员B",
                    ),
                ),
                (
                    "pool",
                    models.ForeignKey(
                        db_column="pool_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bouts",
                        to="fencing_organizer.djangopool",
                        verbose_name="所属小组",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        db_column="status_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pool_bouts",
                        to="fencing_organizer.djangomatchstatustype",
                        verbose_name="比赛状态",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        db_column="winner_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pool_bouts_won",
                        to="fencing_organizer.djangofencer",
                        verbose_name="获胜者",
                    ),
                ),
            ],
            options={
                "verbose_name": "小组赛单场",
                "verbose_name_plural": "小组赛单场",
                "db_table": "pool_bout",
                "ordering": ["pool", "scheduled_time"],
                "indexes": [
                    models.Index(fields=["pool"], name="idx_pool_bout_pool"),
                    models.Index(fields=["status"], name="idx_pool_bout_status"),
                    models.Index(
                        fields=["fencer_a", "fencer_b"], name="idx_pool_bout_fencers"
                    ),
                    models.Index(
                        fields=["scheduled_time"], name="idx_pool_bout_scheduled_time"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="djangopoolbout",
            constraint=models.CheckConstraint(
                check=models.Q(("fencer_a_id__lt", models.F("fencer_b_id"))),
                name="chk_pool_bout_fencer_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="djangopoolbout",
            constraint=models.UniqueConstraint(
                fields=("pool", "fencer_a", "fencer_b"), name="unique_pool_bout_pair"
            ),
        ),
        migrations.AddIndex(
            model_name="djangopool",
            index=models.Index(fields=["event"], name="idx_pool_event"),
        ),
        migrations.AddIndex(
            model_name="djangopool",
            index=models.Index(fields=["piste"], name="idx_pool_piste"),
        ),
        migrations.AddIndex(
            model_name="djangopool",
            index=models.Index(fields=["status"], name="idx_pool_status"),
        ),
        migrations.AddIndex(
            model_name="djangopool",
            index=models.Index(fields=["is_completed"], name="idx_pool_completed"),
        ),
        migrations.AddIndex(
            model_name="djangopool",
            index=models.Index(fields=["start_time"], name="idx_pool_start_time"),
        ),
        migrations.AddConstraint(
            model_name="djangopool",
            constraint=models.UniqueConstraint(
                fields=("event", "pool_number"), name="unique_pool_event_number"
            ),
        ),
        migrations.AddIndex(
            model_name="djangopiste",
            index=models.Index(
                fields=["tournament", "is_available"], name="idx_piste_availability"
            ),
        ),
        migrations.AddIndex(
            model_name="djangopiste",
            index=models.Index(fields=["piste_type"], name="idx_piste_type"),
        ),
        migrations.AddConstraint(
            model_name="djangopiste",
            constraint=models.UniqueConstraint(
                fields=("tournament", "piste_number"),
                name="unique_piste_tournament_number",
            ),
        ),
    ]
