# Generated by Django 4.2.27 on 2025-12-14 08:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fencing_organizer",
            "0007_djangomatchstatustype_djangopiste_djangopool_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="djangofencer",
            options={
                "ordering": ["last_name", "first_name"],
                "verbose_name": "击剑运动员",
                "verbose_name_plural": "击剑运动员",
            },
        ),
        migrations.AlterField(
            model_name="djangofencer",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="出生日期"),
        ),
        migrations.AlterField(
            model_name="djangofencer",
            name="country_code",
            field=models.CharField(
                blank=True,
                help_text="IOC 3字母代码",
                max_length=3,
                null=True,
                verbose_name="国家代码",
            ),
        ),
        migrations.AlterField(
            model_name="djangofencer",
            name="current_ranking",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="当前世界排名"
            ),
        ),
        migrations.AlterField(
            model_name="djangofencer",
            name="display_name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="显示名称"
            ),
        ),
        migrations.AlterField(
            model_name="djangofencer",
            name="fencing_id",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="国际击剑ID",
            ),
        ),
        migrations.AlterField(
            model_name="djangofencer",
            name="first_name",
            field=models.CharField(
                max_length=100,
                validators=[django.core.validators.MinLengthValidator(1)],
                verbose_name="名",
            ),
        ),
        migrations.AlterField(
            model_name="djangofencer",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MEN", "男"),
                    ("WOMEN", "女"),
                    ("MIXED", "混合"),
                    ("OPEN", "公开"),
                ],
                max_length=10,
                null=True,
                verbose_name="性别",
            ),
        ),
        migrations.AlterField(
            model_name="djangofencer",
            name="last_name",
            field=models.CharField(
                max_length=100,
                validators=[django.core.validators.MinLengthValidator(1)],
                verbose_name="姓",
            ),
        ),
        migrations.AlterField(
            model_name="djangofencer",
            name="primary_weapon",
            field=models.CharField(
                blank=True,
                choices=[("FOIL", "花剑"), ("EPEE", "重剑"), ("SABRE", "佩剑")],
                max_length=10,
                null=True,
                verbose_name="主剑种",
            ),
        ),
        migrations.AddIndex(
            model_name="djangofencer",
            index=models.Index(fields=["current_ranking"], name="idx_fencer_ranking"),
        ),
        migrations.AddIndex(
            model_name="djangofencer",
            index=models.Index(fields=["primary_weapon"], name="idx_fencer_weapon"),
        ),
        migrations.AddIndex(
            model_name="djangofencer",
            index=models.Index(fields=["gender"], name="idx_fencer_gender"),
        ),
        migrations.AddIndex(
            model_name="djangofencer",
            index=models.Index(fields=["birth_date"], name="idx_fencer_birth_date"),
        ),
        migrations.AddIndex(
            model_name="djangofencer",
            index=models.Index(fields=["created_at"], name="idx_fencer_created_at"),
        ),
    ]
