# Generated by Django 4.2.27 on 2025-12-14 09:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("fencing_organizer", "0008_alter_djangofencer_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DjangoEventParticipant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "seed_rank",
                    models.IntegerField(blank=True, null=True, verbose_name="种子排名"),
                ),
                (
                    "seed_value",
                    models.FloatField(blank=True, null=True, verbose_name="种子分值"),
                ),
                (
                    "is_confirmed",
                    models.BooleanField(default=True, verbose_name="是否确认参赛"),
                ),
                (
                    "registration_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="报名时间"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="备注")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        db_column="event_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="fencing_organizer.djangoevent",
                        verbose_name="所属项目",
                    ),
                ),
                (
                    "fencer",
                    models.ForeignKey(
                        db_column="fencer_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_participations",
                        to="fencing_organizer.djangofencer",
                        verbose_name="运动员",
                    ),
                ),
            ],
            options={
                "verbose_name": "项目参与者",
                "verbose_name_plural": "项目参与者",
                "db_table": "event_participant",
                "ordering": ["event", "seed_rank"],
            },
        ),
        migrations.CreateModel(
            name="DjangoPoolAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "final_pool_rank",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="最终排名",
                    ),
                ),
                ("victories", models.IntegerField(default=0, verbose_name="胜场数(V)")),
                (
                    "indicator",
                    models.IntegerField(
                        default=0,
                        help_text="TS - TR，不允许直接更新",
                        verbose_name="得失分差(Ind)",
                    ),
                ),
                (
                    "touches_scored",
                    models.IntegerField(default=0, verbose_name="总得分(TS)"),
                ),
                (
                    "touches_received",
                    models.IntegerField(default=0, verbose_name="总失分(TR)"),
                ),
                (
                    "matches_played",
                    models.IntegerField(default=0, verbose_name="已赛场次"),
                ),
                (
                    "is_qualified",
                    models.BooleanField(default=False, verbose_name="是否晋级"),
                ),
                (
                    "qualification_rank",
                    models.IntegerField(blank=True, null=True, verbose_name="晋级排名"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fencer",
                    models.ForeignKey(
                        db_column="fencer_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pool_assignments",
                        to="fencing_organizer.djangofencer",
                        verbose_name="运动员",
                    ),
                ),
                (
                    "pool",
                    models.ForeignKey(
                        db_column="pool_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="fencing_organizer.djangopool",
                        verbose_name="所属小组",
                    ),
                ),
            ],
            options={
                "verbose_name": "小组分配",
                "verbose_name_plural": "小组分配",
                "db_table": "pool_assignment",
                "ordering": ["pool", "final_pool_rank"],
                "indexes": [
                    models.Index(
                        fields=["pool", "is_qualified", "final_pool_rank"],
                        name="idx_pool_assignment_qualified",
                    ),
                    models.Index(fields=["fencer"], name="idx_pool_assignment_fencer"),
                    models.Index(
                        fields=["final_pool_rank"], name="idx_pool_assignment_rank"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="djangopoolassignment",
            constraint=models.UniqueConstraint(
                fields=("pool", "fencer"), name="unique_pool_fencer"
            ),
        ),
        migrations.AddConstraint(
            model_name="djangopoolassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("final_pool_rank__isnull", False)),
                fields=("pool", "final_pool_rank"),
                name="unique_pool_rank",
            ),
        ),
        migrations.AddIndex(
            model_name="djangoeventparticipant",
            index=models.Index(
                fields=["event", "seed_rank"], name="idx_event_participant_seed"
            ),
        ),
        migrations.AddIndex(
            model_name="djangoeventparticipant",
            index=models.Index(fields=["fencer"], name="idx_event_participant_fencer"),
        ),
        migrations.AddIndex(
            model_name="djangoeventparticipant",
            index=models.Index(
                fields=["is_confirmed"], name="idx_event_participant_conf"
            ),
        ),
        migrations.AddConstraint(
            model_name="djangoeventparticipant",
            constraint=models.UniqueConstraint(
                fields=("event", "fencer"), name="unique_event_fencer"
            ),
        ),
    ]
