# Generated by Django 4.2.27 on 2026-02-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fencing_organizer",
            "0009_djangoeventparticipant_djangopoolassignment_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="djangotournament",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLANNING", "计划中"),
                    ("REGISTRATION_OPEN", "报名开放"),
                    ("REGISTRATION_CLOSED", "报名关闭"),
                    ("ONGOING", "进行中"),
                    ("COMPLETED", "已完成"),
                    ("CANCELLED", "已取消"),
                ],
                default="PLANNING",
                max_length=20,
                verbose_name="赛事状态",
            ),
        ),
    ]
