# Generated by Django 4.2.27 on 2026-03-08 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fencing_organizer", "0010_alter_djangotournament_status"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="djangoevent",
            name="idx_event_type",
        ),
        migrations.RemoveIndex(
            model_name="djangoevent",
            name="idx_event_is_team",
        ),
        migrations.AddField(
            model_name="djangoevent",
            name="current_step",
            field=models.IntegerField(default=0, verbose_name="当前编排步骤进度"),
        ),
        migrations.AddField(
            model_name="djangoevent",
            name="de_trees",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="各阶段淘汰赛对阵图(JSON)"
            ),
        ),
        migrations.AddField(
            model_name="djangoevent",
            name="live_ranking",
            field=models.JSONField(
                blank=True, default=list, verbose_name="实时排名快照(JSON)"
            ),
        ),
        migrations.AlterField(
            model_name="djangoevent",
            name="event_type",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                verbose_name="项目类型(如MEN_INDIVIDUAL_FOIL)",
            ),
        ),
        migrations.AlterField(
            model_name="djangoevent",
            name="rule",
            field=models.ForeignKey(
                blank=True,
                db_column="rule_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="fencing_organizer.djangorule",
                verbose_name="赛制规则",
            ),
        ),
        migrations.AlterField(
            model_name="djangoevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("REGISTRATION", "正在报名"),
                    ("ONGOING", "进行中"),
                    ("COMPLETED", "已完成"),
                    ("CANCELLED", "已取消"),
                ],
                default="REGISTRATION",
                max_length=20,
                verbose_name="项目状态",
            ),
        ),
    ]
