# Generated by Django 4.2.27 on 2026-03-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fencing_organizer", "0011_remove_djangoevent_idx_event_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="djangopool",
            options={
                "ordering": ["event", "stage_id", "pool_number"],
                "verbose_name": "小组",
                "verbose_name_plural": "小组",
            },
        ),
        migrations.RemoveConstraint(
            model_name="djangopool",
            name="unique_pool_event_number",
        ),
        migrations.RemoveIndex(
            model_name="djangopool",
            name="idx_pool_piste",
        ),
        migrations.RemoveIndex(
            model_name="djangopool",
            name="idx_pool_completed",
        ),
        migrations.RemoveIndex(
            model_name="djangopool",
            name="idx_pool_start_time",
        ),
        migrations.RemoveField(
            model_name="djangopool",
            name="piste",
        ),
        migrations.RemoveField(
            model_name="djangopool",
            name="pool_letter",
        ),
        migrations.RemoveField(
            model_name="djangopool",
            name="start_time",
        ),
        migrations.AddField(
            model_name="djangopool",
            name="fencer_ids",
            field=models.JSONField(
                blank=True, default=list, verbose_name="组内运动员ID列表(JSON)"
            ),
        ),
        migrations.AddField(
            model_name="djangopool",
            name="is_locked",
            field=models.BooleanField(default=False, verbose_name="是否锁定成绩"),
        ),
        migrations.AddField(
            model_name="djangopool",
            name="results",
            field=models.JSONField(
                blank=True, default=list, verbose_name="比赛结果矩阵(JSON)"
            ),
        ),
        migrations.AddField(
            model_name="djangopool",
            name="stage_id",
            field=models.CharField(default="1", max_length=50, verbose_name="阶段ID"),
        ),
        migrations.AddField(
            model_name="djangopool",
            name="stats",
            field=models.JSONField(
                blank=True, default=list, verbose_name="比赛统计(JSON)"
            ),
        ),
        migrations.AddIndex(
            model_name="djangopool",
            index=models.Index(fields=["stage_id"], name="idx_pool_stage"),
        ),
        migrations.AddConstraint(
            model_name="djangopool",
            constraint=models.UniqueConstraint(
                fields=("event", "stage_id", "pool_number"),
                name="unique_pool_event_stage_number",
            ),
        ),
    ]
