# Generated by Django 4.2.27 on 2026-03-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fencing_organizer", "0012_alter_djangopool_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="djangoevent",
            name="custom_rule_config",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="自定义规则配置"
            ),
        ),
        migrations.AddField(
            model_name="djangorule",
            name="is_preset",
            field=models.BooleanField(default=False, verbose_name="是否为预设规则"),
        ),
        migrations.AddField(
            model_name="djangorule",
            name="preset_code",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="预设代码",
            ),
        ),
        migrations.AddField(
            model_name="djangorule",
            name="stages_config",
            field=models.JSONField(blank=True, default=list, verbose_name="阶段配置"),
        ),
    ]
