# Generated by Django 4.2.27 on 2026-03-16 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fencing_organizer", "0014_seed_predefined_rules"),
    ]

    operations = [
        migrations.AddField(
            model_name="djangopool",
            name="piste",
            field=models.ForeignKey(
                blank=True,
                db_column="piste_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pools",
                to="fencing_organizer.djangopiste",
                verbose_name="分配剑道",
            ),
        ),
    ]
