# Generated by Django 4.2.27 on 2026-03-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fencing_organizer", "0015_add_piste_to_pool"),
    ]

    operations = [
        migrations.AddField(
            model_name="djangopool",
            name="start_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="计划开始时间"
            ),
        ),
    ]
