# Generated by Django 4.2.29 on 2026-03-30 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fencing_organizer", "0016_add_start_time_to_pool"),
    ]

    operations = [
        migrations.AddField(
            model_name="djangotournament",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_tournaments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建者",
            ),
        ),
        migrations.AddField(
            model_name="djangotournament",
            name="schedulers",
            field=models.ManyToManyField(
                blank=True, related_name="assigned_tournaments", to=settings.AUTH_USER_MODEL, verbose_name="编排人员"
            ),
        ),
    ]
