# Generated by Django 4.2.29 on 2026-04-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fencing_organizer", "0018_set_created_by_for_existing_tournaments"),
    ]

    operations = [
        # Add version fields to DjangoTournament
        migrations.AddField(
            model_name='djangotournament',
            name='version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='djangotournament',
            name='last_modified_node',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='djangotournament',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        # Add version fields to DjangoEvent
        migrations.AddField(
            model_name='djangoevent',
            name='version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='djangoevent',
            name='last_modified_node',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='djangoevent',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        # Add version fields to DjangoFencer
        migrations.AddField(
            model_name='djangofencer',
            name='version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='djangofencer',
            name='last_modified_node',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='djangofencer',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        # Add version fields to DjangoPool
        migrations.AddField(
            model_name='djangopool',
            name='version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='djangopool',
            name='last_modified_node',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='djangopool',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        # Add version fields to DjangoPoolBout
        migrations.AddField(
            model_name='djangopoolbout',
            name='version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='djangopoolbout',
            name='last_modified_node',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='djangopoolbout',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        # Add version fields to DjangoPiste
        migrations.AddField(
            model_name='djangopiste',
            name='version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='djangopiste',
            name='last_modified_node',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='djangopiste',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        # Add version fields to DjangoRule
        migrations.AddField(
            model_name='djangorule',
            name='version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='djangorule',
            name='last_modified_node',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='djangorule',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        # Add version fields to DjangoEventParticipant
        migrations.AddField(
            model_name='djangoeventparticipant',
            name='version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='djangoeventparticipant',
            name='last_modified_node',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='djangoeventparticipant',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        # Add version fields to DjangoPoolAssignment
        migrations.AddField(
            model_name='djangopoolassignment',
            name='version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='djangopoolassignment',
            name='last_modified_node',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='djangopoolassignment',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        # Add version fields to DjangoRankingType (lookup table, might not need but adding for consistency)
        migrations.AddField(
            model_name='djangorankingtype',
            name='version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='djangorankingtype',
            name='last_modified_node',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='djangorankingtype',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        # Add version fields to DjangoTournamentStatus (lookup table)
        migrations.AddField(
            model_name='djangotournamentstatus',
            name='version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='djangotournamentstatus',
            name='last_modified_node',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='djangotournamentstatus',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        # Add version fields to DjangoEventType (lookup table)
        migrations.AddField(
            model_name='djangoeventtype',
            name='version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='djangoeventtype',
            name='last_modified_node',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='djangoeventtype',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        # Add version fields to DjangoEventStatus (lookup table)
        migrations.AddField(
            model_name='djangoeventstatus',
            name='version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='djangoeventstatus',
            name='last_modified_node',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='djangoeventstatus',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        # Add version fields to DjangoEliminationType (lookup table)
        migrations.AddField(
            model_name='djangoeliminationtype',
            name='version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='djangoeliminationtype',
            name='last_modified_node',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='djangoeliminationtype',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        # Add version fields to DjangoMatchStatusType (lookup table)
        migrations.AddField(
            model_name='djangomatchstatustype',
            name='version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='djangomatchstatustype',
            name='last_modified_node',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='djangomatchstatustype',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]