# Generated by Django 4.2.29 on 2026-04-11 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fencing_organizer", "0019_add_version_tracking"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="djangoeliminationtype",
            name="last_modified_at",
        ),
        migrations.RemoveField(
            model_name="djangoeliminationtype",
            name="last_modified_node",
        ),
        migrations.RemoveField(
            model_name="djangoeliminationtype",
            name="version",
        ),
        migrations.RemoveField(
            model_name="djangoeventstatus",
            name="last_modified_at",
        ),
        migrations.RemoveField(
            model_name="djangoeventstatus",
            name="last_modified_node",
        ),
        migrations.RemoveField(
            model_name="djangoeventstatus",
            name="version",
        ),
        migrations.RemoveField(
            model_name="djangoeventtype",
            name="last_modified_at",
        ),
        migrations.RemoveField(
            model_name="djangoeventtype",
            name="last_modified_node",
        ),
        migrations.RemoveField(
            model_name="djangoeventtype",
            name="version",
        ),
        migrations.RemoveField(
            model_name="djangomatchstatustype",
            name="last_modified_at",
        ),
        migrations.RemoveField(
            model_name="djangomatchstatustype",
            name="last_modified_node",
        ),
        migrations.RemoveField(
            model_name="djangomatchstatustype",
            name="version",
        ),
        migrations.RemoveField(
            model_name="djangorankingtype",
            name="last_modified_at",
        ),
        migrations.RemoveField(
            model_name="djangorankingtype",
            name="last_modified_node",
        ),
        migrations.RemoveField(
            model_name="djangorankingtype",
            name="version",
        ),
        migrations.RemoveField(
            model_name="djangotournamentstatus",
            name="last_modified_at",
        ),
        migrations.RemoveField(
            model_name="djangotournamentstatus",
            name="last_modified_node",
        ),
        migrations.RemoveField(
            model_name="djangotournamentstatus",
            name="version",
        ),
    ]
